/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'Erik' at '08.10.17 21:10' with Gradle 2.13
 *
 * @author Erik, @date 08.10.17 21:10
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
